---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create Docker instances
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        privileged: true
        command: "{{ item.command | default('/lib/systemd/systemd') }}"
        volumes: "{{ item.volumes | default(omit) }}"
        tmpfs: "{{ item.tmpfs | default(omit) }}"
        capabilities: "{{ item.capabilities | default(omit) }}"
        cgroupns_mode: host
      loop: "{{ molecule_yml.platforms }}"
      register: instances
