---
- name: Destroy
  hosts: localhost
  connection: local
  tasks:
    - name: Destroy Docker instances
      docker_container:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ molecule_yml.platforms }}"
