---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  ansible-lint .
  yamlint .
platforms:
  - name: oraclelinux
    image: oraclelinux:8
    pre_build_image: true
    command: /usr/sbin/init
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN


  - name: ubuntu
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    command: /lib/systemd/systemd
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp


provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: timer,profile_tasks
      deprecation_warnings: false
      stdout_callback: yaml
  inventory:
    group_vars:
      oraclelinux:
        ansible_python_interpreter: auto
      ubuntu:
        ansible_python_interpreter: auto
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
    destroy: destroy.yml

verifier:
  name: ansible
  options:
    v: true

scenario:
  name: default
  test_sequence:
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
