- name: Create
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create a container
      containers.podman.podman_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        privileged: "{{ item.privileged | default(omit) }}"
        volumes: "{{ item.volumes | default(omit) }}"
        capabilities: "{{ item.capabilities | default(omit) }}"
        systemd: "{{ item.systemd | default(omit) }}"
        state: started
        command: "{{ item.command | default('sleep 1d') }}"
        log_driver: json-file
      register: result
      loop: "{{ molecule_yml.platforms }}"

    - name: Create remote_tmp directory
      ansible.builtin.file:
        path: '/tmp/.ansible-{{ ansible_user }}/tmp'
        state: directory
        mode: '0755'