---
# Dependency management (download roles/collections)
dependency:
  name: galaxy


driver:
  name: podman

platforms:
  - name: ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: /lib/systemd/systemd
    privileged: true
    cgroupns_mode: host
    security_opt:
      - label=disable
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        ansible_user: root
  config_options:
    defaults:
      deprecation_warnings: false
      stdout_callback: default   
      remote_tmp: '/tmp/.ansible-${USER}/tmp'

verifier:
  name: ansible

scenario:
  name: podman
  test_sequence:
    - create
    - converge
    - verify
    - destroy
